### ISSUE TITLE
Auto Decide Mobile vs Desktop

### ISSUE THREAD

**Issue by sunyu912** [sunyu912/graduation-assistant#2]
If mobile, we use Table View; Otherwise, we use Default Home View.

**Comment by wangx6f** [comment]
After the modification and testing, it turns out that the Main View works well on mobile device while Table View may need some adjustment.

**Comment by sunyu912** [comment]
If that's the case, let's just hide the Table View for now, since users might be confusing.

**Comment by wangx6f** [comment]
Fixed by hiding the table view.
