### ISSUE TITLE
Text Overlapped by the Two Gray Boxes when you Scroll to the bottom

### ISSUE THREAD

**Issue by sunyu912** [sunyu912/graduation-assistant#7]
Before scrolling to the bottom 

<img width="1214" alt="screen shot 2017-10-02 at 6 30 13 am" src="https://user-images.githubusercontent.com/1639351/31079681-4a493f70-a73b-11e7-9e7e-b957cad7ade3.png">

Scroll to the bottom:

<img width="1156" alt="screen shot 2017-10-02 at 6 30 25 am" src="https://user-images.githubusercontent.com/1639351/31079683-4bce96f6-a73b-11e7-8ce6-e20d74b059cc.png">

**Comment by wangx6f** [comment]
Fixed.
